"use client";

import * as React from "react";
import type { Filing } from "@/generated/prisma/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

type FilingData = {
  filing_id: string;
  filing_type: string;
  filing_date: string;
  generated_by: string;
  generated_at: string;
  property: Record<string, string>;
  closing_date: string;
  purchase_price: string;
  property_type: string;
  transferee: Record<string, string>;
  beneficial_owners: Array<Record<string, string>>;
  seller: Record<string, string>;
  settlement_agent: Record<string, string>;
};

function Section({
  title,
  fields,
}: {
  title: string;
  fields: Array<{ label: string; value: string }>;
}) {
  return (
    <Card className="bg-slate-50">
      <CardHeader>
        <CardTitle>{title}</CardTitle>
      </CardHeader>
      <CardContent className="space-y-1.5">
        {fields.map((field) => (
          <div key={field.label} className="grid grid-cols-2 gap-3 text-sm">
            <p className="font-medium text-slate-600">{field.label}</p>
            <p className="text-slate-900">{field.value || "—"}</p>
          </div>
        ))}
      </CardContent>
    </Card>
  );
}

export function FilingPreview({ filing }: { filing: Filing }) {
  const data = filing.filing_data as FilingData;
  const generatedAt = data.generated_at
    ? new Date(data.generated_at).toLocaleString("en-US")
    : "—";

  return (
    <div className="space-y-3">
      <Card>
        <CardHeader>
          <CardTitle>Generated Filing</CardTitle>
        </CardHeader>
        <CardContent className="space-y-2 text-sm">
          <p>
            <span className="font-medium">Filing ID:</span> {data.filing_id}
          </p>
          <p>
            <span className="font-medium">Generated:</span> {generatedAt}
          </p>
          <p>
            <span className="font-medium">Generated by:</span> {data.generated_by}
          </p>
          <p>
            <span className="font-medium">Status:</span>{" "}
            <span className="rounded bg-emerald-100 px-2 py-0.5 text-xs font-semibold text-emerald-800">
              {filing.status}
            </span>
          </p>
        </CardContent>
      </Card>

      <Section
        title="Part I — Filing Information"
        fields={[
          { label: "Type of filing", value: data.filing_type },
          { label: "Filing date", value: data.filing_date },
        ]}
      />
      <Section
        title="Part II — Transaction Information"
        fields={[
          {
            label: "Property address",
            value: `${data.property.address}, ${data.property.city}, ${data.property.state} ${data.property.zip}`,
          },
          { label: "County", value: data.property.county },
          { label: "Date of closing", value: data.closing_date },
          { label: "Purchase price", value: data.purchase_price },
          { label: "Property type", value: data.property_type },
        ]}
      />
      <Section
        title="Part III — Transferee (Buyer) Information"
        fields={[
          { label: "Name", value: data.transferee.name },
          { label: "Entity type", value: data.transferee.entity_type },
          { label: "EIN", value: data.transferee.ein },
          { label: "Formation state", value: data.transferee.formation_state },
          { label: "Formation date", value: data.transferee.formation_date },
          { label: "Principal address", value: data.transferee.principal_address },
        ]}
      />

      <Card className="bg-slate-50">
        <CardHeader>
          <CardTitle>Part IV — Beneficial Ownership Information</CardTitle>
        </CardHeader>
        <CardContent className="space-y-2">
          {data.beneficial_owners.map((owner, index) => (
            <div key={`owner-${index}`} className="rounded border border-slate-200 bg-white p-3">
              <p className="mb-2 text-sm font-semibold">Beneficial Owner {index + 1}</p>
              <div className="grid grid-cols-2 gap-2 text-sm">
                <p className="text-slate-600">Name</p>
                <p>{owner.full_name || "—"}</p>
                <p className="text-slate-600">Date of birth</p>
                <p>{owner.date_of_birth || "—"}</p>
                <p className="text-slate-600">SSN/ITIN</p>
                <p>{owner.ssn_itin || "—"}</p>
                <p className="text-slate-600">Address</p>
                <p>{owner.address || "—"}</p>
                <p className="text-slate-600">ID Type</p>
                <p>{owner.id_type || "—"}</p>
                <p className="text-slate-600">ID Number</p>
                <p>{owner.id_number || "—"}</p>
                <p className="text-slate-600">Jurisdiction</p>
                <p>{owner.id_jurisdiction || "—"}</p>
              </div>
            </div>
          ))}
        </CardContent>
      </Card>

      <Section
        title="Part V — Transferor (Seller) Information"
        fields={[
          { label: "Name", value: data.seller.name },
          { label: "Address", value: data.seller.address },
          { label: "SSN/EIN", value: data.seller.ssn_ein },
        ]}
      />

      <Section
        title="Part VI — Settlement Agent Information"
        fields={[
          { label: "Company name", value: data.settlement_agent.company_name },
          { label: "Agent name", value: data.settlement_agent.agent_name },
          { label: "License number", value: data.settlement_agent.license_number },
          { label: "Address", value: data.settlement_agent.address },
          { label: "Phone", value: data.settlement_agent.phone },
        ]}
      />

      <div className="flex flex-wrap gap-2">
        <a href={`/api/filings/${filing.id}/pdf`} download>
          <Button>Download PDF</Button>
        </a>
        <Button variant="secondary" disabled>
          Generate Amendment
        </Button>
      </div>
    </div>
  );
}
